import { useState, useCallback, useRef } from "react";

const MAX_HISTORY = 50;
import type { Editor as TiptapEditor } from "@tiptap/core";
import {
  TiptapAPCore,
  type Registry,
  type Executor,
  type AuditEntry,
  type PreflightResult,
  type Change,
} from "tiptap-apcore";
import Editor from "./components/Editor";
import ToolPanel from "./components/ToolPanel";
import type { LogEntry } from "./components/ToolPanel";
import AclSwitcher from "./components/AclSwitcher";
import AuditPanel from "./components/AuditPanel";
import ChatPanel from "./components/ChatPanel";
import MCPDemo from "./components/MCPDemo";

export default function App() {
  const [tab, setTab] = useState<"editor" | "mcp">("editor");
  const [role, setRole] = useState<"readonly" | "editor" | "admin">("admin");
  const [registry, setRegistry] = useState<Registry | null>(null);
  const [executor, setExecutor] = useState<Executor | null>(null);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [showConfirm, setShowConfirm] = useState(false);
  const [historyCount, setHistoryCount] = useState(0);
  const editorRef = useRef<TiptapEditor | null>(null);
  const apcoreRef = useRef<TiptapAPCore | null>(null);
  const htmlHistoryRef = useRef<string[]>([]);

  const [auditLog, setAuditLog] = useState<AuditEntry[]>([]);
  const [remoteAudit, setRemoteAudit] = useState<AuditEntry[]>([]);
  const [pendingPreview, setPendingPreview] = useState<PreflightResult | null>(null);

  const addLog = useCallback((entry: LogEntry) => {
    setLogs((prev) => [entry, ...prev].slice(0, 100));
    // Refresh the ACL audit trail - every call source routes through addLog.
    setAuditLog(apcoreRef.current?.getAuditLog() ?? []);
  }, []);

  /** Merge the server-side ACL audit trail (AI tool calls) into the panel. */
  const handleChatAudit = useCallback((entries: AuditEntry[]) => {
    setRemoteAudit((prev) => [...prev, ...entries]);
  }, []);

  /** Initialize or re-initialize APCore when editor is ready or role changes */
  const initApcore = useCallback(
    (editor: TiptapEditor, currentRole: "readonly" | "editor" | "admin") => {
      try {
        if (!apcoreRef.current) {
          const apcore = new TiptapAPCore(editor, { acl: { role: currentRole }, audit: true });
          apcoreRef.current = apcore;
          setRegistry(apcore.registry);
          setExecutor(apcore.executor);
          addLog({
            type: "info",
            message: `APCore initialized: role=${currentRole}, ${apcore.list().length} modules`,
            timestamp: Date.now(),
          });
        } else {
          // Dynamic update ACL!
          apcoreRef.current.setAcl({ role: currentRole });
          addLog({
            type: "info",
            message: `APCore updated: role=${currentRole}`,
            timestamp: Date.now(),
          });
        }
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        addLog({
          type: "error",
          message: `APCore init/update failed: ${msg}`,
          timestamp: Date.now(),
        });
      }
    },
    [addLog],
  );

  const handleEditorReady = useCallback(
    (editor: TiptapEditor) => {
      editorRef.current = editor;
      initApcore(editor, role);
    },
    [role, initApcore],
  );

  const handleRoleChange = useCallback(
    (newRole: "readonly" | "editor" | "admin") => {
      setRole(newRole);
      if (editorRef.current) {
        initApcore(editorRef.current, newRole);
      }
    },
    [initApcore],
  );

  // ---- Demo scenario handlers ----

  async function demoInsertHeading() {
    if (!executor) return;
    try {
      // First toggle heading
      await executor.call("tiptap.format.toggleHeading", { level: 1 });
      addLog({
        type: "success",
        message: "tiptap.format.toggleHeading({ level: 1 })",
        timestamp: Date.now(),
      });

      // Then insert content
      await executor.call("tiptap.content.insertContent", {
        value: "APCore lets AI directly control your editor",
      });
      addLog({
        type: "success",
        message:
          'tiptap.content.insertContent({ value: "APCore lets AI directly control your editor" })',
        timestamp: Date.now(),
      });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      addLog({ type: "error", message: msg, timestamp: Date.now() });
    }
  }

  async function demoWriteParagraph() {
    if (!executor) return;
    try {
      await executor.call("tiptap.content.insertContent", {
        value:
          "<p>This content was automatically generated by AI using the APCore module. APCore enables AI to safely control your editor, with every action annotated and subject to permission controls.</p>",
      });
      addLog({
        type: "success",
        message: "tiptap.content.insertContent (paragraph)",
        timestamp: Date.now(),
      });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      addLog({ type: "error", message: msg, timestamp: Date.now() });
    }
  }

  async function demoFormat() {
    if (!executor) return;
    try {
      // Select all content
      await executor.call("tiptap.selection.selectAll", {});
      addLog({
        type: "success",
        message: "tiptap.selection.selectAll()",
        timestamp: Date.now(),
      });

      // Toggle bold on selection
      await executor.call("tiptap.format.toggleBold", {});
      addLog({
        type: "success",
        message: "tiptap.format.toggleBold()",
        timestamp: Date.now(),
      });

      // Toggle italic
      await executor.call("tiptap.format.toggleItalic", {});
      addLog({
        type: "success",
        message: "tiptap.format.toggleItalic()",
        timestamp: Date.now(),
      });

      // Toggle bullet list
      await executor.call("tiptap.format.toggleBulletList", {});
      addLog({
        type: "success",
        message: "tiptap.format.toggleBulletList()",
        timestamp: Date.now(),
      });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      addLog({ type: "error", message: msg, timestamp: Date.now() });
    }
  }

  async function demoClearDocument() {
    // Preview the destructive op via the SDK before executing it. validate()
    // predicts the changes and reports whether approval is required, WITHOUT
    // touching the document -- this is what drives the confirmation dialog.
    const apcore = apcoreRef.current;
    if (!apcore) return;
    const preview = await apcore.validate("tiptap.destructive.clearContent", {});
    setPendingPreview(preview);
    setShowConfirm(true);
    addLog({
      type: "info",
      message: `Destructive op intercepted via validate(): requiresApproval=${preview.requiresApproval}, ${preview.predictedChanges?.length ?? 0} predicted change(s)`,
      timestamp: Date.now(),
    });
  }

  async function confirmClear() {
    setShowConfirm(false);
    setPendingPreview(null);
    if (!executor) return;
    try {
      await executor.call("tiptap.destructive.clearContent", {});
      addLog({
        type: "success",
        message: "tiptap.destructive.clearContent() -- confirmed by user",
        timestamp: Date.now(),
      });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      addLog({ type: "error", message: msg, timestamp: Date.now() });
    }
  }

  function cancelClear() {
    setShowConfirm(false);
    setPendingPreview(null);
    addLog({
      type: "info",
      message: "Destructive operation cancelled by user",
      timestamp: Date.now(),
    });
  }

  // ---- Chat integration helpers ----

  function getEditorHtml(): string {
    if (editorRef.current) {
      return editorRef.current.getHTML();
    }
    return "";
  }

  const handleEditorUpdate = useCallback(
    async (html: string) => {
      // Save current HTML to history before applying update
      if (editorRef.current) {
        const currentHtml = editorRef.current.getHTML();
        const history = htmlHistoryRef.current;
        history.push(currentHtml);
        if (history.length > MAX_HISTORY) {
          history.splice(0, history.length - MAX_HISTORY);
        }
        setHistoryCount(history.length);
      }

      if (!executor) return;
      try {
        await executor.call("tiptap.destructive.setContent", { value: html });
        addLog({
          type: "info",
          message: "Editor updated from AI response",
          timestamp: Date.now(),
        });
      } catch (err: unknown) {
        // If setContent fails via executor (e.g. ACL), fall back to direct editor update
        if (editorRef.current) {
          editorRef.current.commands.setContent(html);
          addLog({
            type: "info",
            message: "Editor updated from AI response (direct)",
            timestamp: Date.now(),
          });
        }
      }
    },
    [executor, addLog],
  );

  const handleUndo = useCallback(() => {
    const history = htmlHistoryRef.current;
    if (history.length === 0) return;
    const lastHtml = history.pop()!;
    setHistoryCount(history.length);
    if (editorRef.current) {
      editorRef.current.commands.setContent(lastHtml);
      addLog({
        type: "info",
        message: `Undo: restored previous version (${history.length} remaining)`,
        timestamp: Date.now(),
      });
    }
  }, [addLog]);

  const handleClearHistory = useCallback(() => {
    htmlHistoryRef.current = [];
    setHistoryCount(0);
    addLog({
      type: "info",
      message: "Edit history cleared",
      timestamp: Date.now(),
    });
  }, [addLog]);

  return (
    <>
      <header className="app-header">
        <h1>
          tiptap-<span>apcore</span> Demo
        </h1>
        <p>Let AI safely control your TipTap editor</p>
        <nav className="app-tabs">
          <button
            className={`app-tab ${tab === "editor" ? "active" : ""}`}
            onClick={() => setTab("editor")}
          >
            AI Editor Demo
          </button>
          <button
            className={`app-tab ${tab === "mcp" ? "active" : ""}`}
            onClick={() => setTab("mcp")}
          >
            MCP Server
          </button>
        </nav>
      </header>

      {tab === "editor" ? (
        <div className="app-layout">
          {/* Left: ACL + Module panel */}
          <div>
            <AclSwitcher role={role} onChange={handleRoleChange} />
            <AuditPanel
              entries={[...auditLog, ...remoteAudit].sort((a, b) =>
                a.timestamp.localeCompare(b.timestamp),
              )}
            />
            <ToolPanel registry={registry} executor={executor} onLog={addLog} />
          </div>

          {/* Center: Editor */}
          <Editor onEditorReady={handleEditorReady} />

          {/* Right-1: Chat Panel */}
          <ChatPanel
            getEditorHtml={getEditorHtml}
            role={role}
            onEditorUpdate={handleEditorUpdate}
            onLog={addLog}
            onAudit={handleChatAudit}
            onUndo={handleUndo}
            onClearHistory={handleClearHistory}
            historyCount={historyCount}
            maxHistory={MAX_HISTORY}
          />

          {/* Right-2: Demo scenarios + Log */}
          <div className="demo-panel">
            <div className="card">
              <h2>Demo Scenarios</h2>
              <div className="demo-buttons">
                <button className="demo-btn" onClick={demoInsertHeading}>
                  <div className="demo-btn-title">AI Insert Title</div>
                  <div className="demo-btn-desc">
                    toggleHeading + insertContent
                  </div>
                </button>

                <button className="demo-btn" onClick={demoWriteParagraph}>
                  <div className="demo-btn-title">AI Write a Paragraph</div>
                  <div className="demo-btn-desc">
                    insertContent with HTML paragraph
                  </div>
                </button>

                <button className="demo-btn" onClick={demoFormat}>
                  <div className="demo-btn-title">AI Formatting</div>
                  <div className="demo-btn-desc">
                    selectAll + bold + italic + bulletList
                  </div>
                </button>

                <button
                  className="demo-btn danger"
                  onClick={demoClearDocument}
                >
                  <div className="demo-btn-title">AI Clear Document</div>
                  <div className="demo-btn-desc">
                    clearContent (requires confirmation)
                  </div>
                </button>
              </div>
            </div>

            <div className="card log-panel">
              <h2>
                Output Log
                {logs.length > 0 && (
                  <button
                    className="log-clear-btn"
                    onClick={() => setLogs([])}
                  >
                    Clear
                  </button>
                )}
              </h2>
              <div className="log-entries">
                {logs.length === 0 && (
                  <div
                    style={{
                      fontSize: 12,
                      color: "var(--text-secondary)",
                      padding: 4,
                    }}
                  >
                    No logs yet. Try a demo scenario or chat with AI.
                  </div>
                )}
                {logs.map((entry, i) => (
                  <div key={i} className={`log-entry ${entry.type}`}>
                    <span style={{ opacity: 0.6 }}>
                      {new Date(entry.timestamp).toLocaleTimeString()}
                    </span>{" "}
                    {entry.message}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      ) : (
        <MCPDemo />
      )}

      {/* Confirmation Dialog */}
      {showConfirm && (
        <div className="dialog-overlay" onClick={cancelClear}>
          <div className="dialog-box" onClick={(e) => e.stopPropagation()}>
            <h3>Approve destructive action?</h3>
            <p>
              APCore intercepted this call and ran <code>validate()</code> to
              preview it — <strong>without modifying the document</strong>.
            </p>
            {pendingPreview && (
              <div className="preview-box">
                <div className="preview-flag">
                  requiresApproval:{" "}
                  <code>{String(pendingPreview.requiresApproval)}</code>
                </div>
                <ul className="preview-changes">
                  {(pendingPreview.predictedChanges ?? []).map((c: Change, i: number) => (
                    <li key={i} className="preview-change">
                      <span className="preview-action">{c.action}</span>
                      <span className="preview-target">{c.target}</span>
                      <span className="preview-summary">{c.summary}</span>
                      {typeof c.before === "string" && c.before && (
                        <div className="preview-snapshot">
                          before: <code>{c.before}</code>
                        </div>
                      )}
                    </li>
                  ))}
                </ul>
              </div>
            )}
            <div className="dialog-actions">
              <button className="btn-cancel" onClick={cancelClear}>
                Cancel
              </button>
              <button className="btn-confirm" onClick={confirmClear}>
                Confirm Clear
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
